name: cartoonify
channels:
  - conda-forge
dependencies:
  - python==3.8
  - cmake==3.21.1
  - dlib
  - opencv
  - wheel
  - numpy
  - pandas
  - streamlit
  - datetime
  - opencv-python-headless==4.5.4.60
  - opencv-contrib-python-headless==4.5.4.60
  - face_recognition
  - face-recognition-models
