name: dlib
channels:
  - conda-forge
dependencies:
  - streamlit >= 0.73
  - dlib
  - opencv
  - wheel
  - numpy
  - pandas
  - streamlit
  - datetime
  - face_recognition
  - face-recognition-models
